### ISSUE TITLE
Unable to select msvc toolset for boost version 1.74 on windows

### ISSUE THREAD

**Issue by MarkusJx** [MarkusJx/install-boost#37]
Hi @MarkusJx
Is there a way to specifically target the msvc version of 1.74?
Defining `toolset: msvc` gives the same error posted above, not defining it gives me the mingw version.

Thanks

_Originally posted by @devm18426 in https://github.com/MarkusJx/install-boost/issues/23#issuecomment-1680581981_

**Comment by devm18426** [comment]
Since I copied blindly from the `README` it turns out I wasn't using the latest version...

`uses: MarkusJx/install-boost@v2.4.1`

Changed it to:

`uses: MarkusJx/install-boost@main`

and looks like the msvc version was downloaded (without specifying explicitly).

Sorry for the trouble and thanks for the time.

**Comment by MarkusJx** [comment]
Ah, yeah, you see, that's kind of my bad, I'll change the readme asap

**Comment by devm18426** [comment]
Thanks, sounds good!
